# Generated by Django 5.1.1 on 2024-11-02 21:19

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_noticia_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='noticias/', validators=[landing.models.validate_image]),
        ),
    ]
