# Generated by Django 5.1.1 on 2024-11-02 22:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
