# Generated by Django 5.1.1 on 2024-11-02 22:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
