# Generated by Django 5.1.1 on 2024-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_article_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tipo',
            field=models.CharField(choices=[('noticias', 'Notícias'), ('avisos', 'Avisos'), ('dicas', 'Dicas')], default='noticia', max_length=10),
        ),
    ]
