# Generated by Django 5.1.1 on 2024-11-17 14:32

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_alter_article_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imagem',
            field=models.ImageField(upload_to='noticias/', validators=[landing.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='article',
            name='tipo',
            field=models.CharField(choices=[('noticias', 'Notícias'), ('avisos', 'Avisos'), ('dicas', 'Dicas')], default='noticias', max_length=10),
        ),
    ]
